## CHANGE this to the name of your plugin.
name: DynaTech-therbz

## CHANGE this to your username.
author: ProfElements

## CHANGE this to a meaninful but short description of your plugin.
description: A slimefun addon that add random stuff I want

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.profelements.dynatech.DynaTech

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/ProfElements/DynaTech

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]
softdepend: [ExoticGarden, InfinityExpansion, GriefDefender]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}-therbz

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
